apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: cts571nu8-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/cts571nu8-java-springboot-gitops